//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré par un outil.
//     Version du runtime :4.0.30319.42000
//
//     Les modifications apportées à ce fichier peuvent provoquer un comportement incorrect et seront perdues si
//     le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Me.Utils {
    using System;
    
    
    /// <summary>
    ///   Une classe de ressource fortement typée destinée, entre autres, à la consultation des chaînes localisées.
    /// </summary>
    // Cette classe a été générée automatiquement par la classe StronglyTypedResourceBuilder
    // à l'aide d'un outil, tel que ResGen ou Visual Studio.
    // Pour ajouter ou supprimer un membre, modifiez votre fichier .ResX, puis réexécutez ResGen
    // avec l'option /str ou régénérez votre projet VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Retourne l'instance ResourceManager mise en cache utilisée par cette classe.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Me.Utils.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Remplace la propriété CurrentUICulture du thread actuel pour toutes
        ///   les recherches de ressources à l'aide de cette classe de ressource fortement typée.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Service already installed.
        /// </summary>
        public static string ERROR_AlreadyInstalled {
            get {
                return ResourceManager.GetString("ERROR_AlreadyInstalled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Section already protected.
        /// </summary>
        public static string ERROR_AlreadyProtected {
            get {
                return ResourceManager.GetString("ERROR_AlreadyProtected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Service already started.
        /// </summary>
        public static string ERROR_AlreadyStarted {
            get {
                return ResourceManager.GetString("ERROR_AlreadyStarted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Service already arrested.
        /// </summary>
        public static string ERROR_AlreadyStopped {
            get {
                return ResourceManager.GetString("ERROR_AlreadyStopped", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Service already uninstalled.
        /// </summary>
        public static string ERROR_AlreadyUninstalled {
            get {
                return ResourceManager.GetString("ERROR_AlreadyUninstalled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Section already unprotected.
        /// </summary>
        public static string ERROR_AlreadyUnprotected {
            get {
                return ResourceManager.GetString("ERROR_AlreadyUnprotected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à File is corrupted.
        /// </summary>
        public static string ERROR_FileCorrupted {
            get {
                return ResourceManager.GetString("ERROR_FileCorrupted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à The file is not encrypted.
        /// </summary>
        public static string ERROR_FileNotCrypted {
            get {
                return ResourceManager.GetString("ERROR_FileNotCrypted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à File not found.
        /// </summary>
        public static string ERROR_FileNotFound {
            get {
                return ResourceManager.GetString("ERROR_FileNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à File not found.
        /// </summary>
        public static string ERROR_FileNotFound1 {
            get {
                return ResourceManager.GetString("ERROR_FileNotFound1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à This key already exists.
        /// </summary>
        public static string ERROR_KeyAlreadyExist {
            get {
                return ResourceManager.GetString("ERROR_KeyAlreadyExist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à This key does not exist.
        /// </summary>
        public static string ERROR_KeyNotFind {
            get {
                return ResourceManager.GetString("ERROR_KeyNotFind", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Empty list add applications.
        /// </summary>
        public static string ERROR_ListEmpty {
            get {
                return ResourceManager.GetString("ERROR_ListEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à No return or unknown error.
        /// </summary>
        public static string ERROR_NoReturnedData {
            get {
                return ResourceManager.GetString("ERROR_NoReturnedData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Incorrect arguments.
        /// </summary>
        public static string ERROR_NumArguments {
            get {
                return ResourceManager.GetString("ERROR_NumArguments", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à The service is not installed.
        /// </summary>
        public static string ERROR_ServiceNotInstalled {
            get {
                return ResourceManager.GetString("ERROR_ServiceNotInstalled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à The service is not started.
        /// </summary>
        public static string ERROR_ServiceNotRunning {
            get {
                return ResourceManager.GetString("ERROR_ServiceNotRunning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Successful operation.
        /// </summary>
        public static string ERROR_Success {
            get {
                return ResourceManager.GetString("ERROR_Success", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Unauthorized action.
        /// </summary>
        public static string ERROR_Unauthorized {
            get {
                return ResourceManager.GetString("ERROR_Unauthorized", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Application list available in admin mode.
        /// </summary>
        public static string MESSAGE_ApplicationList {
            get {
                return ResourceManager.GetString("MESSAGE_ApplicationList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Shortcut: {0} ==&gt; Application: {1}.
        /// </summary>
        public static string MESSAGE_ApplicationListEnumeration {
            get {
                return ResourceManager.GetString("MESSAGE_ApplicationListEnumeration", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Choice: {0}.
        /// </summary>
        public static string MESSAGE_Choice {
            get {
                return ResourceManager.GetString("MESSAGE_Choice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Some commands do not work if the service is not installed.
        /// </summary>
        public static string MESSAGE_CommandsUnavailable {
            get {
                return ResourceManager.GetString("MESSAGE_CommandsUnavailable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à IsAdmin ?: {0}.
        /// </summary>
        public static string MESSAGE_IsAdmin {
            get {
                return ResourceManager.GetString("MESSAGE_IsAdmin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à &gt;&gt;&gt;&gt;&gt; ChoiceRunTheProcess job ended successfully.
        /// </summary>
        public static string MESSAGE_JobOk {
            get {
                return ResourceManager.GetString("MESSAGE_JobOk", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à {0} service is installed={1} and is running={2}.
        /// </summary>
        public static string MESSAGE_ServiceStatus {
            get {
                return ResourceManager.GetString("MESSAGE_ServiceStatus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à The service is not found on computer.
        /// </summary>
        public static string MESSAGE_ServiceUnavailable {
            get {
                return ResourceManager.GetString("MESSAGE_ServiceUnavailable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Successfull operation.
        /// </summary>
        public static string MESSAGE_Success {
            get {
                return ResourceManager.GetString("MESSAGE_Success", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à User: {0}.
        /// </summary>
        public static string MESSAGE_User {
            get {
                return ResourceManager.GetString("MESSAGE_User", resourceCulture);
            }
        }
    }
}
